sudo: required
language: generic
services:
  # tell travis we need a copy of docker ready to go
  - docker

# steps that need to occur before run our tests
before_install:
  - docker build -t tzunhei/docker-react-test -f Dockerfile.dev .

# contains all the command needed to run our test suites
script:
  - docker run -e CI=true tzunhei/docker-react-test npm run test

# config to tell travis how deploy to aws
deploy:
  - provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-921802594782"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY