sudo: required
language: generic
services:
  # tell travis we need a copy of docker ready to go
  - docker

# steps that need to occur before run our tests
before_install:
  - docker build -t tzunhei/docker-react-test -f Dockerfile.dev .

# contains all the command needed to run our test suites
script:
  - docker run -e CI=true tzunhei/docker-react-test npm run test
